subject = ["C","C++","C#","Java","C","Python","C","JavaScript","HTML","MySQL"]

print("Length of the list: ",len(subject))
subject.append("Swift")
print("Append add new element of list at last position:",subject)
subject.insert(4,"Kotlin")
print("Insert also add new element but have to mention the positon: ",subject)
subject.remove("HTML")
print("Remove the given element:",subject)
subject.sort()
print("Sorted list alphabetically or ascending:",subject)
subject.reverse()
print("Reverse make it descending order:",subject)
subject.pop()
print("Pop the last element:",subject)

subject2 = subject.copy()
print("Copy all element of subject:",subject2)
subject2.clear()
print("Clear all element:",subject2)
position = subject.index("Java")
print("Index of Java:",position)
Koybar_ace = subject.count("C")
print("Koybar_ace:",Koybar_ace)